### PR TITLE
Update and rename index.html to Mita

### PR DESCRIPTION
**Pull request by Mita-cpu**

### CODE REVIEW

**Review by anthonygraignic — CHANGES_REQUESTED** [review]
Hello, thanks for the pull request !

Unfortunately you made the same mistake as Nothemba and changed the `index.html` rather than the `2021/yearbook.html`. All the details are here https://github.com/GirlCodeZA/glsde101-personal-website/pull/2

You need to add your pic & name to the `2021/yearbook.html` file next to Nothemba.

Please update your Pull Request with the modifications or don't hesitate if you have any question

**Comment by Mita-cpu** [comment]
Thank you, Anthony.

I am still trying to create my website. I will change the
2021/yearbook.html and will let you know when I have a question.

Kind regards,
Mita Raboya

**Comment by Mita-cpu** [comment]
Do I make the changes under Nothemba's file?

Regards,
Mita Raboya

**Comment by anthonygraignic** [comment]
Merged in #32

**Pull request closed without merging**
